=== OpenNeptune/J2EE/J2EE/WebContent/xml/base_schema_indicator_occurrence.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="baseSchemaIndicator_occurence"
	xmlns:tns="baseSchemaIndicator_occurence"
	elementFormDefault="qualified">
	
	<!-- 使用occurrence指示器指定元素出现的次数 -->
	
	<element name="root">
		<complexType>
			<sequence>
				<!-- 通过maxOccurs指示器指定该元素只能出现一次 -->
				<element name="mans" maxOccurs="1"></element>
				<!-- 通过maxOccurs指示器指定该元素出现次数不受限制 -->
				<element name="man" maxOccurs="unbounded"></element>
				<!-- 通过Occurrence指示器指定该元素只能出现0~10次 -->
				<element name="school" minOccurs="1" maxOccurs="10"></element>
			</sequence>
		</complexType>
	</element>
</schema>

=== OpenNeptune/J2EE/J2EE/WebContent/xml/base_schema_indicator_occurrence.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
	xmlns="baseSchemaIndicator_occurence"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="baseSchemaIndicator_occurence base_schema_indicator_occurrence.xsd">
	<mans>只能出现一次</mans>
	<man>可以出现无数次</man>
	<man>可以出现无数次</man>
	<man>可以出现无数次</man>
	<man>可以出现无数次</man>
	<school>只能出现1次到10次之间</school>
	<school>只能出现1次到10次之间</school>
	<school>只能出现1次到10次之间</school>
</root>
